#ifndef __CLUSTERCSR_H_
#define __CLUSTERCSR_H_

/* Venus Block Control Register Map [P.118] */
#define VENUSCLUSTER_CFGREG_OFFSET       0x00
#define VENUSCLUSTER_INTSTATUSREG_OFFSET 0x08
#define VENUSCLUSTER_INTCLEARREG_OFFSET  0x10
#define VENUSCLUSTER_PROGRESSREG_OFFSET  0x18
#define VENUSCLUSTER_RUNTIMEREG_OFFSET   0x20
#define VENUSCLUSTER_NUMRETREG_OFFSET    0x28

/* i's range is 0 ~ 15 */
#define VENUSCLUSTER_RETADDRREG_OFFSET(i) (0x30 + (i * 0x10))
#define VENUSCLUSTER_RETLENREG_OFFSET(i)  (0x38 + (i * 0x10))

#endif /* __CLUSTERCSR_H_ */

