#include "hw/devctrl.h"
#include "hw/addressmap.h"
#include "types.h"
#include "ulib.h"

/*
 * 解开venus dma、 部分或者全部的venus block的硬复位
 * 硬复位：可以向Venus Block中的I-SPM和D-SPM写数据
 * 软复位：Block中的Pico处理器开始运行程序
 */

void devctrl_init(void) {
  // 使能AHB和DMA
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_AHB_DEV_RST_OFFSET, VENUS_AHB_DMA_EN);
  // 使能DEBUG UART
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_APB_DEV_RST_OFFSET, VENUS_DEBUG_UART_EN);
  // Test 2023-4-18: 测试，开启0_00 0_01 1_00 1_01 block
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(0), 0x80000003);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(1), 0x80000003);
  // 解开全部的CLUSTER 和 AXI
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(0), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(1), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(2), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(3), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(4), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(5), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(6), CLUSTER_AXI_BLOCK_ALL_EN);
  // WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(7), CLUSTER_AXI_BLOCK_ALL_EN);
}

