#include "hw/devctrl.h"
#include "hw/addressmap.h"
#include "types.h"
#include "ulib.h"

void devctrl_init(void) {
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_AHB_DEV_RST_OFFSET, VENUS_AHB_DMA_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_APB_DEV_RST_OFFSET, VENUS_DEBUG_UART_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(0), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(1), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(2), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(3), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(4), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(5), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(6), CLUSTER_AXI_BLOCK_ALL_EN);
  WRITE_BURST_32(VENUS_DEVCTRL_ADDR, VENUS_CLUSTER_DEV_RST_OFFSET_CLUSTER(7), CLUSTER_AXI_BLOCK_ALL_EN);
}
